### ISSUE TITLE
fails when seeds.rb is not present

### ISSUE THREAD

**Issue by gwik** [james2m/seedbank#29]
Hi,

Using HEAD, any `rake` command fails when file `db/seeds.rb` is not present.

```
Don't know how to build task 'db:seed:original'
```

I used rake 10.1.0, ruby 2.0.0p247, rails 3.2.13.
`touch db/seeds.rb` fixes it.

Thanks for the gem.

**Comment by fernandodev** [comment]
:+1: Adding `db/seeds.rb` fixed it for me.
