### ISSUE TITLE
db/seeds.rb

### ISSUE THREAD

**Issue by vizjerai** [james2m/seedbank#30]
Just tried out 0.3.0.pre and 0.3.0.pre2 and rake db:seed caused this error.

```
rake aborted!
Don't know how to build task 'db:seed:original'
/bin/ruby_noexec_wrapper:14:in `eval'
/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => db:seed => db:seed:common
(See full trace by running task with --trace)
```

It took a while to figure it out but apparently there is an assumption that there is a ```db/seeds.rb``` file that wasn't there in v0.1.2. Throwing an empty file there fixed the issue and it works again. So... either the code should be updated to allow not having db/seeds.rb or add in the documentation that it is required to work.

**Comment by TahirMehmood** [comment]
same issue 
$ rake db:seeds
rake aborted!
Don't know how to build task 'db:seeds'

(See full trace by running task with --trace)

i have seeds files in db folder
name.seeds.rb

**Comment by james2m** [comment]
@TahirMehmood that gives me no real useful information to go on. If you can share a repository which demonstrates the failure I'll be happy to look. I've never been able to reproduce it so will not attempt a fix until I can.

**Comment by jasontwong** [comment]
Looks like @TahirMehmood is doing

`$ rake db:seeds`

When he should be doing

`$ rake db:seed`
