### ISSUE TITLE
uninitialized constant

### ISSUE THREAD

**Issue by dboyd68** [james2m/seedbank#34]
getting uninitialized constant on the first line of my seed file
User.create(...)

I can run rake db:seed fine withouth seedbank.

I am using mongoid.

Error is:

rake aborted!
uninitialized constant User
//home/user/my_project/db/seeds.rb:4:in `block in define_seed_task'
//home/user/.rvm/gems/ruby-2.0.0-p247@myi/gems/seedbank-0.3.0/lib/seedbank/dsl.rb:24:in`module_eval'
//home/user/.rvm/gems/ruby-2.0.0-p247@myi/gems/seedbank-0.3.0/lib/seedbank/dsl.rb:24:in `block in define_seed_task'
//home/user/.rvm/gems/ruby-2.0.0-p247@myi/bin/ruby_executable_hooks:15:in`eval'
//home/user/.rvm/gems/ruby-2.0.0-p247@myi/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed => db:seed:common => db:seed:original

**Comment by msimkins** [comment]
jeromegn's fix worked for me as well, a +1 for this, it probably can be protected by an ....if defined?(Mongoid) in the main gem

**Comment by ivanovaleksey** [comment]
Mongoid initially [defines](https://github.com/mongodb/mongoid/blob/master/lib/mongoid/railties/database.rake#L18) `db:seed` rake task with `environment` as prerequisite.

But `Rake::Task#clear` [here](https://github.com/james2m/seedbank/blob/master/lib/seedbank/dsl.rb#L6) removes all task's prerequisites.

I created #60 - the main idea is to keep `environment` task in prerequisites list if there was one.
It should help.

**Comment by ivanovaleksey** [comment]
I didn't notice `add_environment_dependency` method [here](https://github.com/james2m/seedbank/blob/master/lib/seedbank/dsl.rb#L60).

But it doesn't work properly because `environment` task is defined after all user tasks and it isn't defined and line 63. Also it should be `:environment` not `':environment'`.
