### ISSUE TITLE
Version 0.3.0 doesn't work with Rails 2.3

### ISSUE THREAD

**Issue by chrisbloom7** [james2m/seedbank#41]
This certainly isn't a high priority given Rails 2.3 and Ruby 1.8.7 are both long deprecated, but maybe it's at least worth changing the dependency requirements.

I'm working on a project that is momentarily stuck using Rails 2.3 LTS and Ruby 1.8.7. I added Seedbank 0.3.0, added a couple simple seed files, and tried running a few of the rake tasks. Each one failed with the following error:

    $ bundle exec rake db:seed:common --trace
    (in /Users/chrisbloom7/Projects/myapp/myapp-redesign)
    Using bundler
    ** Invoke db:seed:common (first_time)
    ** Invoke db:seed:original (first_time)
    ** Invoke db:abort_if_pending_migrations (first_time)
    ** Invoke environment (first_time)
    ** Execute environment
    ** Execute db:abort_if_pending_migrations
    ** Execute db:seed:original
    rake aborted!
    Is a directory - /Users/chrisbloom7/Projects/myapp/myapp-redesign/db/seeds/redesign
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/seedbank-0.3.0/lib/seedbank/dsl.rb:24:in `read'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/seedbank-0.3.0/lib/seedbank/dsl.rb:24:in `define_seed_task'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:634:in `call'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:634:in `execute'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:631:in `each'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
    /Users/chrisbloom7/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/monitor.rb:242:in `synchronize'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:607:in `invoke_prerequisites'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:604:in `each'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:596:in `invoke_with_call_chain'
    /Users/chrisbloom7/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/monitor.rb:242:in `synchronize'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/gems/rake-0.8.7/bin/rake:31
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/bin/rake:23:in `load'
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/bin/rake:23
    /Users/chrisbloom7/.rvm/gems/ruby-1.8.7-p374@myapp/bin/ruby_executable_hooks:15

Here's my `db/` folder layout:

    $ cd db
    $ tree
    .
    |____bootstrap
    | |____.keep
    |____migrate
    | |____.keep
    |____redirect_seed_data.csv
    |____schema.rb
    |____seeds
    | |____redesign
    | | |____stored_credit.seeds.rb
    | |____users.seeds.rb

I downgraded Seedbank to version 0.2.1 and it runs fine.

**Comment by james2m** [comment]
Updated the README.md to refer 2.x rails users to 0.2.1.
