### ISSUE TITLE
Seeds for multiple environments

### ISSUE THREAD

**Issue by thatRailsGuy** [james2m/seedbank#47]
I have a project which has seeds data for multiple environments but not all. Currently I'm using the file format like this: 

    db/seeds/
      bar.seeds.rb
      development/
        users.seeds.rb
      integration/
        users.seeds.rb
      foo.seeds.rb

and the integration/users.seeds.rb is one line like this:

    after "development:users"

Is there a better way to add seeds for multiple environments? Maybe something closer to how it is handled in the gemfile? 

    group :development, :integration do
      ...
    end

**Comment by wyaeld** [comment]
We resolve this my putting the actual seed code under `lib/seeds/` - which makes it easier to test, and then the seeds files end up looking like this

```ruby
puts 'Running Production Seeds'

RoleSeeds.default_roles_and_permissions
CodeSeeds.default_codes
UserSeeds.production_users
```

Is working fine, makes reuse across multiple environments extremely easy to manage

**Comment by jesperronn** [comment]
@wyaeld Awesome tip, which means I could actually clean up and provide seed data on demand in my app. Thanks for sharing :+1:

**Comment by james2m** [comment]
Seem @wyaeld has this covered. As for the group :development, :integration ... suggestion, I'm going to close this unless somebody feels inclined to reopen with a pull request.
