### ISSUE TITLE
Doesn't appear to work in Rails 4.2.4 

### ISSUE THREAD

**Issue by jonathansimmons** [james2m/seedbank#52]
Installed tonight, setup a couple files and rake `rake db:seed` none of the rake files outside of my primary `seeds.rb` file were run.

**Comment by james2m** [comment]
Works fine in 4.2.4 I've a few projects of my own on 4.2.4. Can you give more specifics of your setup and the seeds directory and files. Rake version, Ruby version, contents of your Gemfile.

**Comment by jonathansimmons** [comment]
Ruby 2.2.3
Rails 4.2.4
Rake 10.4.2


Sample Gemfile
```ruby
source 'https://rubygems.org'
# Rails/Ruby
ruby '2.2.3'
gem 'rails', '4.2.4'

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'jbuilder'
gem 'seedbank`

# Development
group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
  gem 'spring'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
  gem 'quiet_assets'
end

```

**Comment by jonathansimmons** [comment]
The seed directory was nothing more than

```
db/seeds/
  development/
    users.seeds.rb
```

**Comment by james2m** [comment]
Thats almost identical to a small project I have. Can you run rake -t=debug db:seed and upload a copy of the output?

**Comment by prem-prakash** [comment]
same here rails 4.2.5

**Comment by prem-prakash** [comment]
It seems that the rake tasks are not being loaded

```bash
% rake db:seed:development                                                                                                                                                              

rake aborted!
Don't know how to build task 'db:seed:development'
```

**Comment by jonathansimmons** [comment]
sorry for the delay here: but mine looks similar to @prem-prakash 

```ruby
$ rake -t db:seed
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:abort_if_pending_migrations
```

**Comment by prem-prakash** [comment]
@james2m I am using rails 4.2.5

**Comment by jasoncox** [comment]
Seedbank requires `db/seeds.rb` so maybe `touch db/seeds.rb` will fix the issue for now?

**Comment by jonathansimmons** [comment]
I can confirm I do have a db/seeds.rb in place and it still does not work. Adding: 

```ruby
puts "seeds files"
```

to seeds.rb does result in that being printed when running `rake db:seed` so the seeds file is still being hit, it's the other files that are ignored.

**Comment by justbaker** [comment]
I can confirm & reproduce issue w/ ActiveRecord v4.2.5. [Reading the seed task](https://github.com/james2m/seedbank/blob/master/lib/tasks/seed.rake), it seems like this occurs when there isn't a `db/seeds.rb` and Rails version > 4.

**Comment by justbaker** [comment]
'Seedbank requires db/seeds.rb'

It attempts to load the file; if it cannot find it, seedbank does not correctly define
`db:seeds:original`, which will result in the error when running `rake db:seed`: `Don't know how to build task 'db:seed:original' `. [See line 36](https://github.com/james2m/seedbank/blob/master/lib/tasks/seed.rake#L36)

**Comment by jonathansimmons** [comment]
I still have this issue even with a `db/seeds.rb` in place. It's worth noting there was no actual code it was just an empty file.

**Comment by justbaker** [comment]
@jonathansimmons Hmm, strange. 
After `touch db/seeds.rb` : 

```
** Invoke db:seed (first_time)
** Invoke db:seed:common (first_time)
** Invoke db:seed:original (first_time)
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:abort_if_pending_migrations
** Execute db:seed:original
** Execute db:seed:common
** Invoke db:seed:test (first_time)
** Invoke db:seed:common 
** Invoke db:seed:test:denials (first_time)
** Invoke db:abort_if_pending_migrations
```
and my seeds work.

Before `touch db/seeds.rb` :

```
** Invoke db:seed (first_time)
** Invoke db:seed:common (first_time)
rake aborted!
Don't know how to build task 'db:seed:original' (see --tasks)
```

**Comment by james2m** [comment]
Awesome @justbaker thanks for nailing it. I'll definitely get onto this over the weekend. Well past due a new release.

**Comment by jonathansimmons** [comment]
So it turns out that my problem is that I was putting files directly in the `/db` and not in a `/seeds` subdirectory.
