### ISSUE TITLE
Shared functionality between seed files

### ISSUE THREAD

**Issue by Midnighter** [james2m/seedbank#55]
I've seen in the documentation how you can add methods and I've also seen the discussion on sharing variables between seed files. My question is about the methods. If I have multiple seed files (in the same environment, e.g., `db/seeds/`) that use the same kind of methods, can I keep the definitions somewhere or should I join all those files into one? Defining something in `db/seeds.rb` and using it in a different file has not worked for me.

**Comment by bradgreens** [comment]
Not my project, but we're doing this at our company by importing modules into the seed class (I'm not really a Ruby guy, so forgive me if I didn't phrase that correctly.)

In `/db/seeds/foo/bar.rb`

```
require File.join(Rails.root, 'db', 'support', 'seed_helpers')

class << self
  include SeedHelpers
end

after [:other_seeds] do
  shared_method('Shared method!')
end
```

In `db/support/seed_helpers.rb`

```
module SeedHelpers
  def shared_method(output)
    puts output
  end
end
```

This pattern works with as many helper files as you wish.

**Comment by Midnighter** [comment]
Stellar! That's exactly what I was looking for.
