### ISSUE TITLE
Seed Heroku via local task w/ param?

### ISSUE THREAD

**Issue by JimW** [james2m/seedbank#63]
In order to use seedbank to seed my staging rails server on Heroku, I currently need to have that personal data in the git repository and I don't want to be forced to have to do that, especially when I open source the project.

I'm thinking of modifying seedbank to accept a parameter that includes this data when it's called through the heroku CLI. Within my seeds, I've already isolated just the data portions for each seed file into a hash within each file.  

Basically, I was thinking to modify the code within seedbank, giving it an option to pull from a parameter hash that if received, rather then that data defined within the seed file itself.  Not sure if my use case is that different from others', but do you think this is a good plan?  Or is there a better way?  

I kind of liked the idea of separating the data in a more formal kind of way within each of the seed files, since that's what people would be editing, keep it cleaner.  Maybe a separate file XXX_seeds.data.rb

**Comment by ivanovaleksey** [comment]
Maybe I am missing something but what is the problem to run `heroku run rake db:seed:foo`?

**Comment by JimW** [comment]
food.seeds.rb has to be within git, right?  I don't want any personal data in there or have to deal with another private git branch just to keep it private.

**Comment by james2m** [comment]
@JimW you probably don't need to actually modify seedbank to do this, you could put the code right in the seeds file couldn't you?

I think of the data in 2 ways, stuff that's not private, but just required to get the app off the ground, that goes into seedbank. Private stuff like user credentials I leave out of production and staging and manually create as it's usually minimal, or I design the app to cater for that being absent. YMMV but I find that balance has never tipped heavily towards the private data.

**Comment by JimW** [comment]
I'm releasing an app that at it's core, deals with google accounts, so all the test data that is used for staging, needs to be valid google accounts (and so private) to actually test stuff while in staging.  I would think that is the case with any kind of server app that allows individual accounts to communicate with other APIs.  So in this case, I just can't find a workflow for dealing with test data on Heroku using seedbank, as it is, if I'm restricted to having to keep that data in github.  Simplest solution I found, was just to find a way to pump it through seedbank during the call from my local machine, where private data could live happily.

**Comment by JimW** [comment]
I ended up putting all my seed data for my app into a single yaml file, where it's easier to see and define everything.  So rather than dealing with separate files and prerequisites via seedbank, I just deal with them all in the original seeds.rb as I'm consuming my yaml from aws s3.  Seedbank is nice though, just not what I need right now.

**Comment by james2m** [comment]
Glad you found a solution.
