### ISSUE TITLE
db/seeds.rb required...should it be?

### ISSUE THREAD

**Issue by Aryk** [james2m/seedbank#65]
Do we really need this file to exist? Right now it crashes if this file doesn't exist:

```ruby
> rake db:seed:common --trace
** Invoke db:seed:common (first_time)
rake aborted!
Don't know how to build task 'db:seed:original' (see --tasks)
```

Seems like it shouldn't be necessary if you use the functionality from this library to put everything into files under db/seeds/*

**Comment by james2m** [comment]
@Aryk try 0.5.0.pre.

**Comment by Aryk** [comment]
will check, thanks

**Comment by james2m** [comment]
@Aryk how'd that work out for you? OK to close?

**Comment by Aryk** [comment]
yup, works!
