### ISSUE TITLE
Class lookup fails from within seed classes (NameError Exception: wrong constant name #<Class:0x007ff918c073d0>)

### ISSUE THREAD

**Issue by cbeckr** [james2m/seedbank#73]
When writing seeds as classes, the use of ``instance_eval`` apparently breaks constant lookup (here: ActiveRecord classes).

To reproduce, put the following in ``db/seeds.rb``:

```
class DbSeed
  def self.run
    field_type_records = FieldType.all
  end
end

DbSeed.run
```

Then, run ``rake db:seed``:
```
$ bundle exec rake db:seed
rake aborted!
NameError: wrong constant name #<Class:0x007fccbe0e66f8>
```

The issue apparently lies with the format of ``Module.nesting.first``, which resolves to ``#<Class:0x007f9f4b2bfa10>::DbSeed``.

Workarounds I devised so far:
- Use global scope to access classes (``::FieldType``)
- Override `const_missing` within the seed class to defer to the next level:

```
  def self.const_missing(name)
    Module.nesting.second.const_missing(name)
  end
```

**Comment by james2m** [comment]
I'm not convinced this is a bug, and not keen on putting in something like the suggested const_missing. You can achieve the goal of writing seeds as classes if you define the class outside of the seed file itself, and call DbSeed.run inside the seed.

Running inside of `instance_eval` allows for `after` blocks and limited variable sharing via `let`.

I'm going to close this as it has an easy work around. I'll happily consider a reopen with PR if it doesn't break existing behavior and doesn't override `const_missing`

**Comment by ashakumari** [comment]
I have been getting similar error too: **NameError: wrong constant name #<Class:0x447eef8>**

I just started using Seedbank (v 0.5.0) and everytime I run rake db:seed, I am running into this issue.  I am trying to add just one record to start with and I haven't been able to take off. I am on Rails 5.1.6 and Ruby 2.3.3.

Does anyone has thoughts on how to resolve this issue? Is anyone using this gem with the latest versions of Ruby on Rails without any issues?

**Comment by james2m** [comment]
@ashakumari Can you post your seeds file here to give a bit more context?

**Comment by ashakumari** [comment]
My seeds.rb is empty. I have modules.seeds.rb under seeds folder which has the simple code as shown below:
`class AppModule < ActiveRecord::Base 
end

AppModule.find_or_create_by(:name => "Example", :label => "Example")`

**Comment by ashakumari** [comment]
Can @james2m or anyone else help me on this?
