### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by bpatram** [james2m/seedbank#76]
Hi, it seems this project has not been actively developed on in quite a few months and has some outstanding issues and pull requests. Are you looking for new maintainers? I use this gem in a few Rails projects and would love to have the confidence that this project will continue to be updated.

**Comment by WaKeMaTTa** [comment]
ping @james2m

**Comment by james2m** [comment]
Yes it is still maintained. Sorry there’s little activity recently, I’m extremely busy. I definitely need to get some of the pull requests in which I will do. 

It’s also been pretty stable for some time so will round off this 0.5.0.pre and get a stable release out. 

Once I’m up on versions I’ll be looking towards the 1.0 which is largely targeting some refactoring and global namespace pollution so some of the PRs will make it into that version. 

Definitely happy to have other hands on if someone wants to help out.
